spring.application.name=task-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow_tasks
spring.datasource.username=taskflow_tasks_user
spring.datasource.password=Taskflow123*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=MiClaveSuperSecretaParaTaskFlowAuthService2026DebeSerLarga
